<a href="https://colab.research.google.com/github/sudemasali/AI-Bootcamp-Projects-/blob/main/BreastCancerCrossVal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#breast cancer veri seti ile 10 fold cross validation implementasyonu

In [35]:
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold, StratifiedKFold, LeaveOneOut, cross_val_score
from sklearn.preprocessing import StandardScaler

In [30]:
#veri setini yükle
X,y = load_breast_cancer(return_X_y= True)

In [41]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

breast_cancer veri setindeki feature lar'ın ölçekleri birbirinden çok farklı olması sebebi ile veriyi standardize ettik. Aksi halde logistic regression iteratif çalışan bir model olduğu için bu durum öğrenmeyi zorlaştırırdı.

In [42]:
model= LogisticRegression(max_iter=1000)

In [44]:

kfold = KFold(n_splits = 10, shuffle = True, random_state= 42)
k_fold_scores = cross_val_score(model,X_scaled,y, cv = kfold)
k_fold_scores

array([0.98245614, 0.98245614, 0.98245614, 0.98245614, 0.98245614,
       0.92982456, 1.        , 0.98245614, 0.94736842, 0.98214286])

In [45]:
# stratified k-fold
stratified_kfold = StratifiedKFold(n_splits=5,shuffle=True,random_state=42)
stratified_kfold_scores = cross_val_score(model, X_scaled, y, cv=stratified_kfold,scoring="accuracy")
stratified_kfold_scores

array([0.97368421, 0.94736842, 0.96491228, 0.99122807, 0.99115044])

In [46]:

#leave one out
loo = LeaveOneOut()
loo_scores = cross_val_score(model, X_scaled, y, cv=loo, scoring="accuracy")
loo_scores

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.