## Çapraz Doğrulama (Cross Validation)

Amaç:
 1. Çapraz doğrulama yöntemlerini karşılaştır

Adımlar:
 1. Veri setini yükle
 2. Basit bir sınıflandırma modeli tanımla
 3. k-fold
 4. stradified k-fold
 5. loo k-fold



In [1]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold, StratifiedKFold, LeaveOneOut, cross_val_score

In [2]:
# Veri setini yükle
X,y = load_iris(return_X_y=True)

In [3]:
model = LogisticRegression(max_iter= 200)

In [8]:
kfold = KFold(n_splits = 5, shuffle = True, random_state= 42)
k_fold_scores = cross_val_score(model,X,y, cv = kfold)
k_fold_scores

array([1.        , 1.        , 0.93333333, 0.96666667, 0.96666667])

In [10]:
# stratified k-fold
stratified_kfold = StratifiedKFold(n_splits=5,shuffle=True,random_state=42)
stratified_kfold_scores = cross_val_score(model, X, y, cv=stratified_kfold,scoring="accuracy")
stratified_kfold_scores

array([1.        , 0.96666667, 0.93333333, 1.        , 0.93333333])

In [11]:
#leave one out
loo = LeaveOneOut()
loo_scores = cross_val_score(model, X, y, cv=loo, scoring="accuracy")
loo_scores

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])